export { createWindow } from './runtime/window';
export { createWindow as window } from './runtime/window';
export type {
  Bounds,
  BoundsInput,
  BoundsOption,
  BoundsResolver,
  DockEventData,
  DragEventData,
  DropZone,
  FreedomPlugin,
  FreedomWindow,
  FreedomWindowOptions,
  InitialPosition,
  MaximizeOptions,
  MinimizeOptions,
  PersistOptions,
  PersistedWindowState,
  PluginContext,
  Point,
  PositioningMode,
  Rect,
  ResizeEventData,
  ResizeHandle,
  Size,
  SnapEdge,
  SnapEventData,
  SnapTarget,
  WindowEventMap,
  WindowMode,
} from './core/types';
